### ISSUE TITLE
Allow diffing files with attachments and history entries

### ISSUE THREAD

**Issue by Narigo** [Narigo/keepass-diff#36]
Thanks to report #35 it looks like attachments are currently not handled at all. If an entry diffs because of attached files, keepass-diff will currently say that there is no difference at all. This should not be the case.

Same for history entries.

**Tasks**
- [ ] Investigate possibilities how to check attachments with `keepass-rs`
- [ ] Investigate possibilities how to check history with `keepass-rs`
- [ ] Add a difference to the output if attachments differ from each other (checking the whole binary)
- [ ] Add a difference if history entries differ from each other (are they compressed binaries as well?)

Use reproducer files from #35 for checking the attachments vs no attachments and create an additional one for changing the current attachment with something else.

**Comment by PaBox** [comment]
Is this still gonna be fixed? Because diffing without diffing EVERYTHING is essentially quite useless. It would be nice to see this feature in the near future, though I saw that you created an issue on `keepass-rs` after having problems with the attachments in `keepass-rs` and it still hasnt been answered. For now it would be nice to at least compare the name and filesize, while it is not a perfect workaround, you could still list all the files with another flag added to the command. 

Apart from this problem, this is a great tool and I really hope you keep the work up :)

**Comment by Narigo** [comment]
Hi @PaBox and thank you for your message!

This tool doesn't really do too much though, it only checks which entries differ from each other. The entries come from the underlying dependency `keepass-rs`. As long as it doesn't allow opening and checking any information of an attachment, I can't really do anything in this regard.

Please try to reach out to @sseemayer and check whether he's able to contribute to `keepass-rs` still. He's been very kind and helpful to this project before as he has re-written most of the integration code when he did some breaking changes to his module. It looks like he wasn't very active lately - there are a couple of cool open PRs in `keepass-rs` by @DavidVentura last year regarding that weren't merged or commented on yet. Maybe he wants to hand over maintenance to someone else...?

**Comment by sseemayer** [comment]
thanks for the ping and the kind words.

You are right in that I have less spare time to spend on maintaining open source code than I had previously, so I would be happy to accept a co-maintainer on the project if that helps in moving progress along.

**Comment by DavidVentura** [comment]
I can give this a shot in my keepass fork -- however I don't feel like my rust skills are good enough to be a maintainer

**Comment by DavidVentura** [comment]
I've looked at this - the biggest thing missing is that the `Meta` header is not currently stored in the original `keepass-rs`. When I was trying to implement write support on the DB I got this partially implemented ([here](https://github.com/DavidVentura/libkeepass-rs/blob/next/src/db.rs#L193)), extending this is a fairly small amount of work, but now I remember that this branch had drifted "significantly" from the original

**Comment by Narigo** [comment]
@sergiofagostinho yes, that would definitely be a good idea - the problem is that the `keepass-rs` is currently not supporting attachments at all and hence `keepass-diff` cannot access information about included files...

@DavidVentura about:
> I don't feel like my rust skills are good enough to be a maintainer

I'd say that maintainers need motivation to learn new things and have time to spare. I'd see that as an opportunity to grow 😉
